baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Data Management and Visualization with R"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Aitor Ameztegui"
  bio = ""
  job = "Researcher/Lecturer"
  location = "University of Lleida"
  gravatarEmail = "aitor.ameztegui@eagrof.udl.cat"
  # Your profile picture
#  picture = ""ยบ
  twitter = "multivac42"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio Cloud"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://rstudio.cloud/spaces/27211/join?access_code=aHODPtNn5L3JspKWeCMOnmC94jEBRM%2FmVJfm4p4t"



[[menu.footer]]
  weight = 1
  identifier = "Lleida"
  name = "University of Lleida"
  pre = "<i class='fa fa-university fa-lg'></i>"
  url = "http://udl.cat/"
[[menu.footer]]
  weight = 2
  name = "RStudio Cloud"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/spaces/27211/join?access_code=aHODPtNn5L3JspKWeCMOnmC94jEBRM%2FmVJfm4p4t"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/ameztegui/111022_data_management_visualization"
[[menu.footer]]


[params]
  dateFormat = "January 2, 2006"
  background = "img/background2.png"
  favicon = "img/udl_logo.ico"
